project:
  type: book
  output-dir: ../docs

book:
  title: "rABM tutorial"
  chapters:
    - index.qmd
    - quick_start_JP.qmd
    - model_library_JP.qmd
    - rABM_classes_JP.qmd
    - state_JP.qmd

format:
  html:
    toc: true
    number-sections: False
