---
title: "11. Core functions"
format: html
number-sections: False
editor: visual
---

::: callout-note
rABMで実装されている関数のうち、特に重要なものを列挙します。詳細は各関数のヘルプページをご覧ください。

【注意】このページはアップデート中です。ほとんどの関数は以下の表ではまだ網羅されていません。（26/4/7）
:::

## Gameオブジェクトの操作

| 関数            | 機能                 | 補足 |
|-----------------|----------------------|------|
| `add_field`     | フィールドの追加     |      |
| `remove_field`  | フィールドの削除     |      |
| `replace_field` | フィールドの入れ替え |      |

## Seriesオブジェクトの操作

| 関数            | ラベル             | 補足 |
|-----------------|--------------------|------|
| `add_chunk`     | チャンクの追加     |      |
| `remove_chunk`  | チャンクの削除     |      |
| `replace_chunk` | チャンクの入れ替え |      |

## モデル

| 関数 | ラベル | 補足 |
|------------------------|------------------------|------------------------|
| `model_schelling_segregation` | T. Schelling (1971)の空間分居モデル |  |
| `model_hero_coward` | NetLogoのHeros and Cowardsモデル |  |
| `model_fire_spread` | NetLogoのforest fireモデル |  |
| `model_knapsack_ga` | 遺伝的アルゴリズムに基づいてナップザック問題を解くモデル |  |
| `model_opinion_jager` | Jager & Amblard (2005)による意見ダイナミクスモデル | 原典に加えて多様なネットワークや多次元の意見をサポート |
| `model_party_laver` | Laver (2005)による政党の政策ポジション動態モデル |  |

## Stateフィールド作成補助

| 関数 | ラベル | 補足 |
|------------------------|------------------------|------------------------|
| `make_group_labels` | `group_prop`に従ってグループラベルを作成 |  |
| `make_grid_neighborhood` | 2Dの碁盤目状のグリッドの隣接グリッド番号をリスト化 | `return_as = "network"` で隣接行列を作成 |
|  |  |  |

## Actフィールド作成補助

| 関数 | ラベル | 補足 |
|------------------------|------------------------|------------------------|
| `sample2` | `` `sample` ``と機能上は全く同じだが、xが長さ1の数字だった場合にベクトルの長さと解釈されてしまう問題を回避 |  |
| `sample_weighted` | ケース×各オプションの選択確率ウェイトのデータ型に対してベクトル計算を行うことで、sampleよりも大幅に速く計算。 | 複数選択も可。復元抽出・非復元抽出のいずれも可。 |
| `act_ga` | 遺伝的アルゴリズムに基づくフィールドの更新 | ２値、多値、数値いずれの型にも対応 |
| `move_coord` | エージェントの移動先座標を現状のエージェントの位置と目標地点、移動速度から計算 | 目標地点の代わりにラジアン（目標角度）でも指定可能 |
