---
title: "rABM Tutorial"
editor: visual
---

**rABM**はRでエージェント・ベースド・モデリング（ABM）を行うためのパッケージです。**R**はABMのようなシミュレーションを行う上で計算実行速度自体は速いとは言えませんが、代わりに直感的な操作性と豊富な統計パッケージに恵まれた言語です。このRの特性を生かして、**rABM**では次の三つの設計思想を大切にして作られています。

-   **直感的な操作性**: 標準的なRユーザーが簡単にABMに取り組めるように、Rの標準的な記法や設計思想を最大限尊重すること

-   **柔軟な拡張性**: さまざまな拡張を自由にできること

-   **総合的な効率性**：ABMの構想から、実行、分析までをトータルで見た場合に、様々な試行錯誤が速く効率的にでき、結果的に迅速な分析作業が行えること

rABMがぜひとも皆様の研究のお役に立てることを祈っています。

::: {style="text-align: right;"}
rABM開発チーム
:::

　　　　　　　

# 日本語版

-   [1. Quick start guide](quick_start_JP.qmd)
-   [2. model library](model_library_JP.qmd)
-   [3. rABMオブジェクトの構成](rABM_classes_JP.qmd)
-   [4. state & active state](state_JP.qmd)
-   [5. plot_FUN](plot_FUN_JP.qmd)
-   [6. act_FUN](act_FUN_JP.qmd)
-   [7. run_Game](run_Game_JP.qmd)
-   [8. stop_FUN](stop_FUN_JP.qmd)
-   [9. report_FUN](report_FUN_JP.qmd)
-   [10. Series](Series_JP.qmd)
-   [11. Core functions](Core_functions_JP.qmd)

# English Version

Coming soon...

※パッケージへのご意見やご提案、バグの報告等は、GithubページのIssues（<https://github.com/KeiichiSatoh/rABM/issues>）にお寄せいただくか、管理者（佐藤圭一・一橋大学、keiichi.satoh \[at\] r.hit-u.ac.jp）までお寄せください。
