// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// grid_index_rc2lin_cpp
IntegerVector grid_index_rc2lin_cpp(NumericMatrix rc, int n_row, int n_col, bool check_bounds);
RcppExport SEXP _rABM_grid_index_rc2lin_cpp(SEXP rcSEXP, SEXP n_rowSEXP, SEXP n_colSEXP, SEXP check_boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type rc(rcSEXP);
    Rcpp::traits::input_parameter< int >::type n_row(n_rowSEXP);
    Rcpp::traits::input_parameter< int >::type n_col(n_colSEXP);
    Rcpp::traits::input_parameter< bool >::type check_bounds(check_boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_index_rc2lin_cpp(rc, n_row, n_col, check_bounds));
    return rcpp_result_gen;
END_RCPP
}
// grid_index_lin2rc_cpp
IntegerMatrix grid_index_lin2rc_cpp(NumericVector idx, int n_row, int n_col, bool check_bounds);
RcppExport SEXP _rABM_grid_index_lin2rc_cpp(SEXP idxSEXP, SEXP n_rowSEXP, SEXP n_colSEXP, SEXP check_boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_row(n_rowSEXP);
    Rcpp::traits::input_parameter< int >::type n_col(n_colSEXP);
    Rcpp::traits::input_parameter< bool >::type check_bounds(check_boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_index_lin2rc_cpp(idx, n_row, n_col, check_bounds));
    return rcpp_result_gen;
END_RCPP
}
// grid_neighbors_core
NumericMatrix grid_neighbors_core(NumericMatrix mat, IntegerVector posit, bool moore, bool include_self, bool torus);
RcppExport SEXP _rABM_grid_neighbors_core(SEXP matSEXP, SEXP positSEXP, SEXP mooreSEXP, SEXP include_selfSEXP, SEXP torusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type posit(positSEXP);
    Rcpp::traits::input_parameter< bool >::type moore(mooreSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    Rcpp::traits::input_parameter< bool >::type torus(torusSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_neighbors_core(mat, posit, moore, include_self, torus));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rABM_grid_index_rc2lin_cpp", (DL_FUNC) &_rABM_grid_index_rc2lin_cpp, 4},
    {"_rABM_grid_index_lin2rc_cpp", (DL_FUNC) &_rABM_grid_index_lin2rc_cpp, 4},
    {"_rABM_grid_neighbors_core", (DL_FUNC) &_rABM_grid_neighbors_core, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rABM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
