# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert (row, col) coordinates to linear indices (internal Rcpp backend)
#'
#' Internal C++ backend for \code{\link{grid_index}}. Not intended to be
#' called directly by users.
#'
#' @param rc A two-column numeric matrix of \code{(row, col)} coordinates.
#' @param n_row Number of rows in the grid.
#' @param n_col Number of columns in the grid. Only used when
#'   \code{check_bounds = TRUE}.
#' @param check_bounds Logical. If \code{TRUE}, out-of-bounds coordinates
#'   raise an error.
#' @return An integer vector of linear indices.
#' @noRd
grid_index_rc2lin_cpp <- function(rc, n_row, n_col, check_bounds) {
    .Call(`_rABM_grid_index_rc2lin_cpp`, rc, n_row, n_col, check_bounds)
}

#' Convert linear indices to (row, col) coordinates (internal Rcpp backend)
#'
#' Internal C++ backend for \code{\link{grid_index}}. Not intended to be
#' called directly by users.
#'
#' @param idx A numeric vector of linear indices.
#' @param n_row Number of rows in the grid.
#' @param n_col Number of columns in the grid. Only used when
#'   \code{check_bounds = TRUE}.
#' @param check_bounds Logical. If \code{TRUE}, out-of-bounds indices
#'   raise an error.
#' @return A two-column integer matrix with columns \code{row} and
#'   \code{col}.
#' @noRd
grid_index_lin2rc_cpp <- function(idx, n_row, n_col, check_bounds) {
    .Call(`_rABM_grid_index_lin2rc_cpp`, idx, n_row, n_col, check_bounds)
}

#' Compute grid neighbor values (internal Rcpp backend)
#'
#' Internal C++ backend for \code{\link{grid_neighbors}}. Not intended to
#' be called directly by users; \code{grid_neighbors()} performs input
#' validation and post-processing (\code{FUN}, \code{simplify}) around
#' this function.
#'
#' @param mat A numeric (double) matrix to read neighbor values from.
#' @param posit An integer vector of 1-based linear (column-major)
#'   indices into \code{mat}.
#' @param moore Logical. \code{TRUE} for the 8-direction Moore
#'   neighborhood, \code{FALSE} for the 4-direction von Neumann
#'   neighborhood.
#' @param include_self Logical. If \code{TRUE}, an extra \code{"self"}
#'   column holding \code{mat[posit]} is appended.
#' @param torus Logical. If \code{TRUE}, out-of-bounds neighbors wrap
#'   around to the opposite edge (periodic boundary conditions). If
#'   \code{FALSE}, out-of-bounds neighbors are \code{NA}.
#'
#' @return A numeric matrix with \code{length(posit)} rows and one column
#'   per direction (\code{"U"}, \code{"D"}, \code{"L"}, \code{"R"}, and,
#'   for the Moore neighborhood, also \code{"UL"}, \code{"UR"},
#'   \code{"DL"}, \code{"DR"}; plus \code{"self"} when
#'   \code{include_self = TRUE}). Row names are \code{posit} coerced to
#'   character.
#' @noRd
grid_neighbors_core <- function(mat, posit, moore, include_self, torus) {
    .Call(`_rABM_grid_neighbors_core`, mat, posit, moore, include_self, torus)
}

