#' Run an ABM Series
#'
#' @description
#' `run_Series()` executes stored code chunks in an [`ABM_Series`] object
#' in a specified order. Chunks are evaluated sequentially in a dedicated
#' environment, so objects created in earlier chunks (e.g., `x <- 1`) can be
#' referenced by later chunks (e.g., `y <- x * 2`).
#'
#' Default objects stored in `Series$default` are first loaded into the execution
#' environment, then optionally overwritten by `input`.
#'
#' @param Series An object of class `"ABM_Series"`.
#' @param series_plan A plan specifying which chunks to execute and in what order.
#' - `NULL` (default): run all chunks in `Series$chunks` in their stored order.
#' - Character vector: chunk names to run (must exist in `names(Series$chunks)`).
#' - Numeric/integer vector: chunk indices to run (1-based).
#' @param input Optional objects to inject into the execution environment.
#' These objects overwrite entries in `Series$default` before execution.
#' Functions are allowed. If unnamed, names are auto-generated by the internal
#' formatter.
#' @param series_seed Random seed for the series run. If `NULL`, a seed is generated
#' from the current system time.
#' @param simplify_output Logical. If `TRUE`, return only the resulting objects
#' (i.e., a named list created from the execution environment). If `FALSE`, return a
#' list with objects and metadata such as the plan, seed, error log, and elapsed time.
#' @param verbose Logical. If `TRUE`, print the execution plan and step-by-step
#' progress messages (including errors).
#' @param parent Parent environment for the execution environment `V`.
#' Use `parent.frame()` (default) to allow chunks to access objects/functions
#' from the calling context. For more reproducible runs, consider a more isolated
#' parent such as `baseenv()` or `emptyenv()`, and pass required objects explicitly
#' via `default` and `input`.
#' @param on_error Behavior when an error occurs while executing a chunk.
#' - `"continue"` (default): store the error in `error_log` and continue to the next chunk.
#' - `"stop"`: stop immediately after storing the error in `error_log`.
#' @param keep Optional character vector of names to keep in the returned objects.
#' If `NULL` (default), all objects in the execution environment are returned.
#' If specified, the returned objects (or `out$values`) are subset to these names.
#' Names not found are ignored with a warning.
#'
#' @return
#' If `simplify_output = TRUE`, a named list of objects created in the execution
#' environment (optionally subset by `keep`).
#'
#' If `simplify_output = FALSE`, a list with:
#' \describe{
#'   \item{values}{A named list of objects created in the execution environment
#'   (optionally subset by `keep`).}
#'   \item{series_plan}{Character vector of executed chunk names.}
#'   \item{series_seed}{The seed used for the run.}
#'   \item{error_log}{A list of captured error conditions (if any), keyed by step.}
#'   \item{implementation_took}{Elapsed time as a character string (`HH:MM:SS.mmm`).}
#' }
#'
#' @details
#' Chunks are evaluated using `eval()` in a dedicated environment `V` created by
#' `list2env()`. The parent of `V` is controlled by the `parent` argument.
#'
#' Errors in individual chunks are handled according to `on_error`.
#'
#' @examples
#' S <- ABM_Series(
#'   chunk_expr = list(
#'     init = chunk({ x <- 1; y <- 2 }),
#'     calc = chunk({ z <- add2(x, y) })
#'   ),
#'   default = list(
#'     add2 = function(a, b) a + b
#'   )
#' )
#'
#' # Run the series
#' out <- run_Series(S, verbose = FALSE)
#' out$values$z
#'
#' # Run only a subset by chunk name
#' out2 <- run_Series(S, series_plan = c("init"), verbose = FALSE)
#'
#' # Inject objects before running
#' out3 <- run_Series(
#'   S,
#'   input = list(x = 10),
#'   verbose = FALSE
#' )
#' out3$values$z
#'
#' # Stop on the first error
#' out4 <- run_Series(S, on_error = "stop", verbose = FALSE)
#'
#' # Keep only selected objects in output
#' out5 <- run_Series(S, keep = c("x", "z"), verbose = FALSE)
#' names(out5$values)
#'
#' @seealso [ABM_Series()], [chunk()]
#' @export
run_Series <- function(Series,
                       series_plan = NULL,
                       input = NULL,
                       series_seed = NULL,
                       simplify_output = FALSE,
                       verbose = TRUE,
                       parent = parent.frame(),
                       on_error = c("continue", "stop"),
                       keep = NULL){

  # ----- match args -----
  on_error <- match.arg(on_error)

  # ----- validation ------
  stopifnot("'Series' must be a class of 'ABM_Series'." = inherits(Series, "ABM_Series"))
  stopifnot("'Series$chunks' must be a list." = is.list(Series$chunks))

  chunk_names <- names(Series$chunks)
  if (is.null(chunk_names) || anyNA(chunk_names) || any(chunk_names == "")) {
    stop("'Series$chunks' must be a named list with non-empty names.")
  }

  # keep
  if (!is.null(keep)) {
    if (!is.character(keep) || anyNA(keep) || any(keep == "")) {
      stop("'keep' must be NULL or a character vector of non-empty names.")
    }
    keep <- unique(keep)
  }

  # ----- series_plan -----
  if (is.null(series_plan)) {
    series_plan_idx <- seq_along(chunk_names)
  } else if (is.character(series_plan)) {
    series_plan_idx <- match(series_plan, chunk_names)
    if (anyNA(series_plan_idx)) {
      NA_name <- unique(series_plan[is.na(series_plan_idx)])
      stop("No corresponding chunk exists: ", paste(NA_name, collapse = ", "))
    }
  } else {
    series_plan_idx <- suppressWarnings(as.integer(series_plan))
    if (anyNA(series_plan_idx)) {
      stop("'series_plan' must be NULL, character, or numeric/integer indices.")
    }
    ok <- series_plan_idx >= 1L & series_plan_idx <= length(chunk_names)
    if (any(!ok)) {
      bad <- unique(series_plan_idx[!ok])
      stop("'series_plan' index out of range: ", paste(bad, collapse = ", "))
    }
  }

  series_plan_formatted <- chunk_names[series_plan_idx]

  # ------- input -----------
  input_list <- .format_input(
    x = input,
    expr = substitute(input),
    prefix = "input"
  )
  if (is.null(input_list)) input_list <- list()

  # ------- update defaults ----------
  default_list <- Series$default
  if (is.null(default_list)) default_list <- list()

  for (nm in names(input_list)) {
    default_list[[nm]] <- input_list[[nm]]
  }

  # ------ create an environment (V) ---------------
  V <- list2env(default_list, parent = parent)

  # ------ seed -------
  if (is.null(series_seed)) series_seed <- as.integer(Sys.time())
  set.seed(seed = series_seed)

  # ----- error_log ---
  error_log <- list()

  # ------ announce the series_plan -----------------------
  if (isTRUE(verbose)) {
    cat("[Series plan]\n")
    cat(paste(series_plan_formatted, collapse = " -> "), "\n\n")
    cat("Series implementing...\n")
  }

  # start_time
  start_time <- Sys.time()

  # ------ implementation of the series_plan ----------
  for (i in seq_along(series_plan_formatted)) {
    nm <- series_plan_formatted[i]

    if (isTRUE(verbose)) {
      cat("  Step ", i, ": ", nm, "\n", sep = "")
    }

    tryCatch(
      eval(Series$chunks[[nm]], envir = V),
      error = function(e) {
        key <- paste0("step", i, "_", nm)
        error_log[[key]] <- e

        if (isTRUE(verbose)) {
          cat("    ERROR: ", conditionMessage(e), "\n", sep = "")
        }

        if (identical(on_error, "stop")) {
          stop(e)
        }
        invisible(NULL)
      }
    )
  }

  # end_time
  end_time <- Sys.time()

  if (isTRUE(verbose)) {
    cat("Series implementation DONE!\n")
  }

  # ------ collect values ------
  values_out <- as.list(V)

  # keep (subset)
  if (!is.null(keep)) {
    missing <- setdiff(keep, names(values_out))
    if (length(missing)) {
      warning("Some names in 'keep' were not found and will be ignored: ",
              paste(missing, collapse = ", "))
    }
    keep2 <- intersect(keep, names(values_out))
    values_out <- values_out[keep2]
  }

  # ------ output ------
  if (isTRUE(simplify_output)) {
    out <- values_out
  } else {
    time_taken <- as.numeric(difftime(end_time, start_time, units = "secs"))
    hours <- floor(time_taken / 3600)
    minutes <- floor((time_taken %% 3600) / 60)
    seconds <- floor(time_taken %% 60)
    milliseconds <- round((time_taken %% 1) * 1000)
    time_hms <- sprintf("%02d:%02d:%02d.%03d", hours, minutes, seconds, milliseconds)

    out <- list(
      values = values_out,
      series_plan = series_plan_formatted,
      series_seed = series_seed,
      error_log = error_log,
      implementation_took = time_hms
    )
  }

  out
}
