#' Normalize user input into a named list
#'
#' Internal utility used by `run_Series()` to normalize the `input` argument.
#'
#' - A single object is wrapped into a list.
#' - An unnamed single object may have its name inferred from the call
#'   (via `expr`, typically `substitute(x)` at the caller).
#' - Unnamed multiple inputs are automatically named using `prefix` (e.g.
#'   `"input1"`, `"input2"`, ...).
#'
#' This helper is intentionally kept private to `run_Series.R`: it exists to
#' support `run_Series(input = ...)`'s convenience auto-naming, and is not
#' used elsewhere in the package (in particular, `Series(default = ...)`
#' requires a fully named list explicitly, rather than relying on this
#' auto-naming behavior -- see `Series()`).
#'
#' @param x An input object to be normalized.
#' @param expr The unevaluated expression corresponding to `x`
#'   (typically obtained via `substitute(x)` at the caller).
#' @param prefix A prefix used to generate names when automatic naming is required.
#'
#' @return A named list, or `NULL` if `x` is `NULL`.
#'
#' @keywords internal
.format_input <- function(x, expr, prefix = "Z") {
  if (is.null(x)) return(NULL)

  # normalize to list
  if (is.list(x) && !is.object(x)) {
    x_list <- x
  } else {
    x_list <- list(x)
  }

  # name check / fill
  x_names <- names(x_list)
  if (!is.null(x_names)) {
    if (anyNA(x_names) || any(x_names == "")) {
      stop("Put names to all elements.")
    }
  } else if (length(x_list) == 1L && is.symbol(expr)) {
    names(x_list) <- deparse(expr)
  } else {
    names(x_list) <- paste0(prefix, seq_along(x_list))
  }

  x_list
}

#' Run an ABM Series
#'
#' @description
#' `run_Series()` executes stored code chunks in an [Series()] object
#' in a specified order. Chunks are evaluated sequentially in a dedicated
#' environment, so objects created in earlier chunks (e.g., `x <- 1`) can be
#' referenced by later chunks (e.g., `y <- x * 2`).
#'
#' Default objects stored in `S$default` are first loaded into the execution
#' environment, then optionally overwritten by `input`.
#'
#' @param S An object of class `"ABM_Series"`.
#' @param series_plan A plan specifying which chunks to execute and in what order.
#' - `NULL` (default): run all chunks in `S$chunks` in their stored order.
#' - Character vector: chunk names to run (must exist in `names(S$chunks)`).
#' - Numeric/integer vector: chunk indices to run (1-based). Every element
#'   must be a whole number (e.g. `2`, `2.0`); non-integer values
#'   (e.g. `2.5`) raise an error rather than being silently truncated.
#' @param input Optional objects to inject into the execution environment.
#' These objects overwrite entries in `S$default` before execution.
#' Functions are allowed, and so is `NULL` (an entry set to `NULL` via
#' `input` remains present in the execution environment with value `NULL`,
#' rather than being removed). If unnamed, names are auto-generated by the
#' internal formatter.
#' @param series_seed Random seed for the series run. If `NULL`, a seed is
#' generated automatically (see Details).
#' @param simplify_output Logical. If `TRUE`, return only the resulting objects
#' (i.e., a named list created from the execution environment). If `FALSE`, return a
#' list with objects and metadata such as the plan, seed, error log, and elapsed time.
#' @param verbose Logical. If `TRUE`, print the execution plan and step-by-step
#' progress messages (including errors).
#' @param parent Parent environment for the execution environment `V`.
#' Use `parent.frame()` (default) to allow chunks to access objects/functions
#' from the calling context. For more reproducible runs, consider a more isolated
#' parent such as `baseenv()` or `emptyenv()`, and pass required objects explicitly
#' via `default` and `input`.
#' @param on_error Behavior when an error occurs while executing a chunk.
#' - `"continue"` (default): store the error in `error_log` and continue to the next chunk.
#' - `"stop"`: store the error in `error_log`, then stop executing further
#'   chunks and return normally with whatever was accumulated so far (the
#'   partial `values`/`error_log`/etc.). This does **not** raise an
#'   uncaught error out of `run_Series()` itself -- see Details.
#' @param keep Optional character vector of names to keep in the returned objects.
#' If `NULL` (default), all objects in the execution environment are returned.
#' If specified, the returned objects (or `out$values`) are subset to these names.
#' Names not found are ignored with a warning.
#'
#' @return
#' If `simplify_output = TRUE`, a named list of objects created in the execution
#' environment (optionally subset by `keep`).
#'
#' If `simplify_output = FALSE`, a list with:
#' \describe{
#'   \item{values}{A named list of objects created in the execution environment
#'   (optionally subset by `keep`).}
#'   \item{series_plan}{Character vector of executed chunk names.}
#'   \item{series_seed}{The seed used for the run.}
#'   \item{error_log}{A list of captured error conditions (if any), keyed by step.}
#'   \item{implementation_took}{Elapsed time as a character string (`HH:MM:SS.mmm`).}
#' }
#'
#' @details
#' Chunks are evaluated using `eval()` in a dedicated environment `V` created by
#' `list2env()`. The parent of `V` is controlled by the `parent` argument.
#'
#' Errors in individual chunks are captured with `tryCatch()` around each
#' chunk's evaluation, so a failing chunk never aborts the whole
#' `run_Series()` call: with `on_error = "continue"` (the default), execution
#' simply moves on to the next chunk; with `on_error = "stop"`, the remaining
#' chunks are skipped (the `for` loop is exited via `break`, not by
#' re-raising the error), and `run_Series()` still returns its usual result
#' -- including whatever was captured in `error_log` -- rather than
#' propagating an uncaught error to the caller.
#'
#' If `series_seed` is `NULL`, a seed is drawn via
#' `sample.int(.Machine$integer.max, 1L)` (which relies on R's own
#' auto-initialized RNG state) and recorded in the return value regardless
#' of whether it was supplied or auto-generated, mirroring the approach used
#' by `run_Game()`.
#'
#' @examples
#' step1 <- Chunk({ x <- 1; y <- 2 })
#' step2 <- Chunk({ z <- add2(x, y) })
#'
#' S <- Series(
#'   step1,
#'   step2,
#'   default = list(add2 = function(a, b) a + b)
#' )
#'
#' # Run the series
#' out <- run_Series(S, verbose = FALSE)
#' out$values$z
#'
#' # Run only a subset by chunk name
#' out2 <- run_Series(S, series_plan = "step1", verbose = FALSE)
#'
#' # Inject objects before running
#' out3 <- run_Series(S, input = list(x = 10), verbose = FALSE)
#' out3$values$z
#'
#' # Stop on the first error -- execution halts after the failing chunk,
#' # but run_Series() still returns normally with the partial results and
#' # the captured error in error_log.
#' step_bad <- Chunk({ stop("boom") })
#' step_after <- Chunk({ never_runs <- TRUE })
#' S_err <- Series(step1, step_bad, step_after)
#' out4 <- run_Series(S_err, on_error = "stop", verbose = FALSE)
#' names(out4$error_log)
#' out4$values$never_runs  # NULL: step_after was never executed
#'
#' # Keep only selected objects in output
#' out5 <- run_Series(S, keep = c("x", "z"), verbose = FALSE)
#' names(out5$values)
#'
#' @seealso [Series()], [Chunk()]
#' @export
run_Series <- function(S,
                       series_plan = NULL,
                       input = NULL,
                       series_seed = NULL,
                       simplify_output = FALSE,
                       verbose = TRUE,
                       parent = parent.frame(),
                       on_error = c("continue", "stop"),
                       keep = NULL) {

  # ----- match args -----
  on_error <- match.arg(on_error)

  # ----- validation ------
  stopifnot("'S' must be an object of class 'ABM_Series'." = inherits(S, "ABM_Series"))
  stopifnot("'S$chunks' must be a list." = is.list(S$chunks))

  chunk_names <- names(S$chunks)
  if (is.null(chunk_names) || anyNA(chunk_names) || any(chunk_names == "")) {
    stop("'S$chunks' must be a named list with non-empty names.")
  }

  # keep
  if (!is.null(keep)) {
    if (!is.character(keep) || anyNA(keep) || any(keep == "")) {
      stop("'keep' must be NULL or a character vector of non-empty names.")
    }
    keep <- unique(keep)
  }

  # ----- series_plan -----
  if (is.null(series_plan)) {
    series_plan_idx <- seq_along(chunk_names)
  } else if (is.character(series_plan)) {
    series_plan_idx <- match(series_plan, chunk_names)
    if (anyNA(series_plan_idx)) {
      NA_name <- unique(series_plan[is.na(series_plan_idx)])
      stop("No corresponding chunk exists: ", paste(NA_name, collapse = ", "))
    }
  } else {
    if (!is.numeric(series_plan) || anyNA(series_plan) || any(series_plan %% 1 != 0)) {
      stop("'series_plan' must be NULL, character, or a vector of whole-number indices.")
    }
    series_plan_idx <- as.integer(series_plan)
    ok <- series_plan_idx >= 1L & series_plan_idx <= length(chunk_names)
    if (any(!ok)) {
      bad <- unique(series_plan_idx[!ok])
      stop("'series_plan' index out of range: ", paste(bad, collapse = ", "))
    }
  }

  series_plan_formatted <- chunk_names[series_plan_idx]

  # ------- input -----------
  input_list <- .format_input(
    x = input,
    expr = substitute(input),
    prefix = "input"
  )
  if (is.null(input_list)) input_list <- list()

  # ------- update defaults ----------
  default_list <- S$default
  if (is.null(default_list)) default_list <- list()

  # Use single-bracket assignment so that an explicit NULL in 'input'
  # (e.g. input = list(x = NULL)) overwrites 'x' with NULL rather than
  # removing it from default_list -- `[[<-` would delete the element on
  # NULL assignment, but `[<-` preserves it.
  for (nm in names(input_list)) {
    default_list[nm] <- input_list[nm]
  }

  # ------ create an environment (V) ---------------
  V <- list2env(default_list, parent = parent)

  # ------ seed -------
  # sample.int() draws from the RNG's own auto-initialized state, avoiding
  # the Y2038-style overflow risk of as.integer(Sys.time()) (see run_Game()).
  if (is.null(series_seed)) series_seed <- sample.int(.Machine$integer.max, 1L)
  set.seed(seed = series_seed)

  # ----- error_log ---
  error_log <- list()

  # ------ announce the series_plan -----------------------
  if (isTRUE(verbose)) {
    cat("[Series plan]\n")
    cat(paste(series_plan_formatted, collapse = " -> "), "\n\n")
    cat("Series implementing...\n")
  }

  # start_time
  start_time <- Sys.time()

  # ------ implementation of the series_plan ----------
  for (i in seq_along(series_plan_formatted)) {
    nm <- series_plan_formatted[i]

    if (isTRUE(verbose)) {
      cat("  Step ", i, ": ", nm, "\n", sep = "")
    }

    # stop_now is set by the error handler below (via <<-) when
    # on_error = "stop" and this chunk errors; it is read right after
    # tryCatch() returns to break out of the for loop. The error itself is
    # never re-raised here (unlike a bare stop(e) inside the handler, which
    # would propagate past this tryCatch and abort run_Series() entirely,
    # preventing it from returning error_log/values at all).
    stop_now <- FALSE

    tryCatch(
      eval(S$chunks[[nm]], envir = V),
      error = function(e) {
        key <- paste0("step", i, "_", nm)
        error_log[[key]] <<- e

        if (isTRUE(verbose)) {
          cat("    ERROR: ", conditionMessage(e), "\n", sep = "")
        }

        if (identical(on_error, "stop")) {
          stop_now <<- TRUE
        }
        invisible(NULL)
      }
    )

    if (stop_now) break
  }

  # end_time
  end_time <- Sys.time()

  if (isTRUE(verbose)) {
    cat("Series implementation DONE!\n")
  }

  # ------ collect values ------
  values_out <- as.list(V)

  # keep (subset)
  if (!is.null(keep)) {
    missing <- setdiff(keep, names(values_out))
    if (length(missing)) {
      warning("Some names in 'keep' were not found and will be ignored: ",
              paste(missing, collapse = ", "))
    }
    keep2 <- intersect(keep, names(values_out))
    values_out <- values_out[keep2]
  }

  # ------ output ------
  if (isTRUE(simplify_output)) {
    out <- values_out
  } else {
    time_taken   <- as.numeric(difftime(end_time, start_time, units = "secs"))
    total_ms     <- floor(time_taken * 1000)
    hours        <- total_ms %/% 3600000L
    minutes      <- (total_ms %% 3600000L) %/% 60000L
    seconds      <- (total_ms %% 60000L) %/% 1000L
    milliseconds <- total_ms %% 1000L
    time_hms     <- sprintf("%02d:%02d:%02d.%03d", hours, minutes, seconds, milliseconds)

    out <- list(
      values             = values_out,
      series_plan        = series_plan_formatted,
      series_seed        = series_seed,
      error_log          = error_log,
      implementation_took = time_hms
    )
  }

  out
}
